pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: buildFront
    steps:
    - task: Npm@1
      displayName: npm ci
      inputs:
        command: 'ci'
    - task: Npm@1
      displayName: fill prod environments
      inputs:
        command: 'custom'
        customCommand: 'run fillDefaultProdEnv -- -buildNumber $(Build.BuildId)'
    - task: Npm@1
      displayName: build to deploy folder
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: CopyFiles@2
      displayName: copy dist to docker artifact
      inputs:
        SourceFolder: 'dist/Olympiad-Front'
        Contents: '**'
        TargetFolder: 'deploy/olympiad-front-build'
    - publish: deploy
      artifact: olympiad-front-pack